name: Version, Tag, Release & Package

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  versioning-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      version: ${{ steps.set_job_outputs.outputs.version }}
      full_tag: ${{ steps.set_job_outputs.outputs.full_tag }}
      is_latest: ${{ steps.set_job_outputs.outputs.is_latest }}
      should_process: ${{ steps.check_version.outputs.should_process }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "CURRENT_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Get PR details and determine version type
        run: |
          PR_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}")
          
          PR_TITLE=$(echo "$PR_DATA" | jq -r '.title // ""' | tr -d '\n\r')
          PR_BODY=$(echo "$PR_DATA" | jq -r '.body // ""')
          
          echo "PR_TITLE<<EOF" >> $GITHUB_ENV
          echo "$PR_TITLE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          PR_BODY_B64=$(echo "$PR_BODY" | base64 -w 0)
          echo "PR_BODY_B64=${PR_BODY_B64}" >> $GITHUB_ENV
          
          VERSION_TYPE=""
          HAS_VERSION_TAG="false"
          
          if echo "$PR_TITLE" | grep -qi "[@#]breakingchange\|[@#]breaking\|[@#]major"; then
            VERSION_TYPE="major"
            HAS_VERSION_TAG="true"
          elif echo "$PR_TITLE" | grep -qi "[@#]feat\|[@#]feature\|[@#]minor"; then
            VERSION_TYPE="minor"
            HAS_VERSION_TAG="true"
          elif echo "$PR_TITLE" | grep -qi "[@#]fix\|[@#]hotfix\|[@#]patch"; then
            VERSION_TYPE="patch"
            HAS_VERSION_TAG="true"
          else
            VERSION_TYPE="none"
            HAS_VERSION_TAG="false"
          fi
          
          echo "VERSION_TYPE=${VERSION_TYPE}" >> $GITHUB_ENV
          echo "HAS_VERSION_TAG=${HAS_VERSION_TAG}" >> $GITHUB_ENV

      - name: Check if we should process version/release
        id: check_version
        run: |
          TARGET_BRANCH="${{ github.base_ref }}"
          HAS_VERSION_TAG="${{ env.HAS_VERSION_TAG }}"
          
          SHOULD_PROCESS="false"
          
          if [[ "$HAS_VERSION_TAG" == "true" ]]; then
            SHOULD_PROCESS="true"
          elif [[ "$TARGET_BRANCH" == "main" ]]; then
            SHOULD_PROCESS="true"
          else
            SHOULD_PROCESS="false"
          fi
          
          echo "SHOULD_PROCESS=${SHOULD_PROCESS}" >> $GITHUB_ENV
          echo "should_process=${SHOULD_PROCESS}" >> $GITHUB_OUTPUT

      - name: Increment version based on PR title tags
        id: increment_version
        if: env.SHOULD_PROCESS == 'true'
        run: |
          CURRENT_VERSION=${{ env.CURRENT_VERSION }}
          VERSION_TYPE=${{ env.VERSION_TYPE }}
          TARGET_BRANCH="${{ github.base_ref }}"
          HAS_VERSION_TAG="${{ env.HAS_VERSION_TAG }}"
          
          CLEAN_VERSION=$(echo $CURRENT_VERSION | sed 's/-pre-prod//')
          
          if [[ "$TARGET_BRANCH" == "main" && "$HAS_VERSION_TAG" == "false" ]]; then
            NEW_VERSION="$CLEAN_VERSION"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN_VERSION"
            
            case $VERSION_TYPE in
              major)
                MAJOR=$((MAJOR + 1))
                MINOR=0
                PATCH=0
                ;;
              minor)
                MINOR=$((MINOR + 1))
                PATCH=0
                ;;
              patch)
                PATCH=$((PATCH + 1))
                ;;
            esac
            
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          
          if [[ "$TARGET_BRANCH" == "develop" ]]; then
            FULL_TAG="${NEW_VERSION}-pre-prod"
            IS_LATEST="false"
          elif [[ "$TARGET_BRANCH" == "main" ]]; then
            FULL_TAG="${NEW_VERSION}"
            IS_LATEST="true"
          fi
          
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "FULL_TAG=$FULL_TAG" >> $GITHUB_ENV
          echo "IS_LATEST=$IS_LATEST" >> $GITHUB_ENV

      - name: Extract changelog from PR body
        if: env.SHOULD_PROCESS == 'true'
        run: |
          PR_BODY=$(echo "${{ env.PR_BODY_B64 }}" | base64 -d)
          
          if echo "$PR_BODY" | grep -q -i -E "[@#](changelog|changes|release.notes?)"; then
            CHANGELOG=$(echo "$PR_BODY" | sed -n -E '/[@#](changelog|changes|release.notes?)/I,$p' | sed '1d' | sed '/^[[:space:]]*$/d')
          else
            if [[ "${{ github.base_ref }}" == "main" && "${{ env.HAS_VERSION_TAG }}" == "false" ]]; then
              CHANGELOG="- Production release of version ${{ env.FULL_TAG }}"
            else
              case ${{ env.VERSION_TYPE }} in
                major)
                  CHANGELOG="- Breaking changes in version ${{ env.FULL_TAG }}"
                  ;;
                minor)
                  CHANGELOG="- New features in version ${{ env.FULL_TAG }}"
                  ;;
                patch)
                  CHANGELOG="- Bug fixes in version ${{ env.FULL_TAG }}"
                  ;;
                *)
                  CHANGELOG="- Update to version ${{ env.FULL_TAG }}"
                  ;;
              esac
            fi
          fi
          
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="- Update to version ${{ env.FULL_TAG }}"
          fi
          
          CHANGELOG_B64=$(echo "$CHANGELOG" | base64 -w 0)
          echo "CHANGELOG_B64=${CHANGELOG_B64}" >> $GITHUB_ENV

      - name: Update version in package.json
        id: update_version
        if: env.SHOULD_PROCESS == 'true' && env.HAS_VERSION_TAG == 'true'
        run: |
          jq --arg version "${{ env.NEW_VERSION }}" '.version = $version' package.json > tmp.json && mv tmp.json package.json

      - name: Commit and push updated package.json
        if: env.SHOULD_PROCESS == 'true' && env.HAS_VERSION_TAG == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "Update version to ${{ env.NEW_VERSION }} [skip ci]"
          git push origin ${{ github.ref_name }}

      - name: Remove old latest tag
        if: env.SHOULD_PROCESS == 'true' && env.IS_LATEST == 'true'
        run: |
          if git tag -l | grep -q "^latest$"; then
            git tag -d latest || true
            git push origin :refs/tags/latest || true
          fi

      - name: Create Git tags
        if: env.SHOULD_PROCESS == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ env.FULL_TAG }}
          git push origin ${{ env.FULL_TAG }}
          if [[ "${{ env.IS_LATEST }}" == "true" ]]; then
            git tag latest
            git push origin latest
          fi

      - name: Create GitHub Release
        if: env.SHOULD_PROCESS == 'true'
        run: |
          CHANGELOG_DECODED=$(echo "$CHANGELOG_B64" | base64 -d)
          if [[ "${{ github.base_ref }}" == "main" && "${{ env.HAS_VERSION_TAG }}" == "false" ]]; then
            VERSION_ICON="🚀"
            VERSION_DISPLAY="Production Release"
          else
            case ${{ env.VERSION_TYPE }} in
              major) VERSION_ICON="🔥"; VERSION_DISPLAY="Breaking Changes" ;;
              minor) VERSION_ICON="✨"; VERSION_DISPLAY="New Features" ;;
              patch) VERSION_ICON="🔧"; VERSION_DISPLAY="Bug Fixes" ;;
              *) VERSION_ICON="📦"; VERSION_DISPLAY="Update" ;;
            esac
          fi
          PR_TITLE="${{ env.PR_TITLE }}"
          RELEASE_PAYLOAD=$(jq -n \
            --arg tag_name "${{ env.FULL_TAG }}" \
            --arg name "${VERSION_ICON} Release ${{ env.FULL_TAG }}" \
            --arg changelog "$CHANGELOG_DECODED" \
            --arg full_tag "${{ env.FULL_TAG }}" \
            --arg source_branch "${{ github.event.pull_request.head.ref }}" \
            --arg target_branch "${{ github.base_ref }}" \
            --arg pr_author "${{ github.event.pull_request.user.login }}" \
            --arg version_display "$VERSION_DISPLAY" \
            --arg pr_title "$PR_TITLE" \
            --arg is_latest_str "$([[ "${{ env.IS_LATEST }}" == "true" ]] && echo "true" || echo "false")" \
            --argjson prerelease "$([[ "${{ env.IS_LATEST }}" != "true" ]] && echo true || echo false)" \
            '{
              tag_name: $tag_name,
              name: $name,
              body: ("## Changelog\n\n" + $changelog + "\n\n## Tags\n- **Version**: `" + $full_tag + "`" + (if ($is_latest_str == "true") then "\n- **Latest**: `latest`" else "" end) + "\n\n## Docker Package\n\n```bash\n# Pull specific version\ndocker pull ghcr.io/track-train/front:" + $full_tag + (if ($is_latest_str == "true") then "\n# Pull latest stable\ndocker pull ghcr.io/track-train/front:latest" else "\n# Pull latest pre-release\ndocker pull ghcr.io/track-train/front:pre-release" end) + "\n```\n\n## Information\n\n- **PR Title**: `" + $pr_title + "`\n- **Version Type**: " + $version_display + "\n- **Source branch**: `" + $source_branch + "`\n- **Target branch**: `" + $target_branch + "`\n- **Release type**: " + (if ($is_latest_str == "true") then "**Stable**" else "**Pre-production**" end) + "\n- **PR author**: @" + $pr_author),
              prerelease: $prerelease,
              make_latest: $is_latest_str
            }')
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/${{ github.repository }}/releases" \
            -d "$RELEASE_PAYLOAD")
          if echo "$RESPONSE" | jq -e '.html_url' > /dev/null; then
            RELEASE_URL=$(echo "$RESPONSE" | jq -r '.html_url')
            echo "Release created successfully: $RELEASE_URL"
          else
            echo "Failed to create release"
            echo "$RESPONSE"
            exit 1
          fi

      - name: Set job outputs
        id: set_job_outputs
        if: env.SHOULD_PROCESS == 'true'
        run: |
          echo "version=${{ env.NEW_VERSION }}" >> $GITHUB_OUTPUT
          echo "full_tag=${{ env.FULL_TAG }}" >> $GITHUB_OUTPUT
          echo "is_latest=${{ env.IS_LATEST }}" >> $GITHUB_OUTPUT

  build-and-deploy-image:
    needs: versioning-and-release
    if: needs.versioning-and-release.outputs.should_process == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare Docker tags
        id: prepare_tags
        run: |
          TAG="${{ needs.versioning-and-release.outputs.full_tag }}"
          if [[ -z "$TAG" ]]; then
            VERSION=$(jq -r '.version' package.json | sed 's/-pre-prod//')
            if [[ "${{ github.base_ref }}" == "develop" ]]; then
              TAG="${VERSION}-pre-prod"
            else
              TAG="$VERSION"
            fi
          fi
          
          TAGS="ghcr.io/track-train/front:${TAG}"
          
          if [[ "${{ needs.versioning-and-release.outputs.is_latest }}" == "true" ]]; then
            TAGS="${TAGS},ghcr.io/track-train/front:latest"
          else
            TAGS="${TAGS},ghcr.io/track-train/front:pre-release"
          fi
          
          echo "DOCKER_TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          target: prod
          tags: ${{ env.DOCKER_TAGS }}
          labels: |
            org.opencontainers.image.title=Express Template Application
            org.opencontainers.image.description=Express.js application with automated versioning
            org.opencontainers.image.version=${{ needs.versioning-and-release.outputs.full_tag }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}

      - name: Deployment summary
        run: |
          echo "## Deployment successful!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Package created" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: \`${{ needs.versioning-and-release.outputs.full_tag }}\`" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ needs.versioning-and-release.outputs.is_latest }}" == "true" ]]; then
            echo "- **Latest**: \`latest\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Pre-release**: \`pre-release\`" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Docker commands" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "docker pull ghcr.io/track-train/front:${{ needs.versioning-and-release.outputs.full_tag }}" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ needs.versioning-and-release.outputs.is_latest }}" == "true" ]]; then
            echo "docker pull ghcr.io/track-train/front:latest" >> $GITHUB_STEP_SUMMARY
          else
            echo "docker pull ghcr.io/track-train/front:pre-release" >> $GITHUB_STEP_SUMMARY
          fi
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### package.json" >> $GITHUB_STEP_SUMMARY
          echo "- Version in package.json: \`${{ needs.versioning-and-release.outputs.version }}\` (clean version)" >> $GITHUB_STEP_SUMMARY