volumes:
  node_modules:

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: trackntrain_frontend
    ports:
      - '5173:5173'
    volumes:
      - node_modules:/app/node_modules
      - ./src:/app/src
